### ISSUE TITLE
bug: Application sometimes doesn't respond when workflow finishes running

### ISSUE THREAD

**Issue by vladfrangu** [sapphiredev/sapphiredev#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Sometimes the app doesn't respond

### Steps To Reproduce

1. Use the app

### Expected behavior

It always responds

### Additional context

idfk what you want me to put here

**Comment by favna** [comment]
This should be resolved now that we're using CF KV and with the recent fixes
